// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6XyG7Ug57dotffyYjieX1Jx4ANLH2SgE',
    appId: '1:281313294545:web:a3b556b74c45e50bf1adf0',
    messagingSenderId: '281313294545',
    projectId: 'nutrimind-ai-a5072',
    authDomain: 'nutrimind-ai-a5072.firebaseapp.com',
    storageBucket: 'nutrimind-ai-a5072.firebasestorage.app',
    measurementId: 'G-FCPK30NQZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0r9odBNP9LWAZ3yt1GNwu6_nCOo0aWtI',
    appId: '1:281313294545:android:de8f57ef4a21bec8f1adf0',
    messagingSenderId: '281313294545',
    projectId: 'nutrimind-ai-a5072',
    storageBucket: 'nutrimind-ai-a5072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbN3k2ZiJMqWRD84aIZbIRDVbIoeSOTsE',
    appId: '1:281313294545:ios:fc3d74a698729936f1adf0',
    messagingSenderId: '281313294545',
    projectId: 'nutrimind-ai-a5072',
    storageBucket: 'nutrimind-ai-a5072.firebasestorage.app',
    iosBundleId: 'com.example.menna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbN3k2ZiJMqWRD84aIZbIRDVbIoeSOTsE',
    appId: '1:281313294545:ios:fc3d74a698729936f1adf0',
    messagingSenderId: '281313294545',
    projectId: 'nutrimind-ai-a5072',
    storageBucket: 'nutrimind-ai-a5072.firebasestorage.app',
    iosBundleId: 'com.example.menna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6XyG7Ug57dotffyYjieX1Jx4ANLH2SgE',
    appId: '1:281313294545:web:123174a4e6690f70f1adf0',
    messagingSenderId: '281313294545',
    projectId: 'nutrimind-ai-a5072',
    authDomain: 'nutrimind-ai-a5072.firebaseapp.com',
    storageBucket: 'nutrimind-ai-a5072.firebasestorage.app',
    measurementId: 'G-D8S7EE8D4B',
  );
}
